import { useEffect, useRef, useState } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useEmployees, useBranches } from "@/hooks/useSupabaseData";
import { calculatePayroll } from "@/data/mockData";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent } from "@/components/ui/dialog";
import { FileText, Printer, Search } from "lucide-react";
import type { Tables } from "@/integrations/supabase/types";
import { formatDate, formatCurrency } from "@/lib/utils";

type Payslip = Tables<"payslips">;
type Employee = Tables<"employees">;

const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

function PayslipView({ slip, employee, branchName }: { slip: Payslip; employee: Employee; branchName: string }) {
  const period = `${MONTHS[slip.period_month - 1]} ${slip.period_year}`;
  return (
    <div id="payslip-print" className="bg-white text-gray-900 font-sans" style={{ minWidth: 480 }}>
      <div className="flex items-center justify-between border-b-2 border-[#2B3990] pb-4 mb-4">
        <div className="flex items-center gap-3">
          <img src="/logo.jpeg" alt="Whiterose" className="h-12 w-auto rounded" />
          <div>
            <p className="font-bold text-[#2B3990] text-base leading-tight">Whiterose Venyou Enterprises Ltd</p>
            <p className="text-xs text-gray-500">P.O Box 514-80401, Mombasa · NSSF No: 2446614X</p>
          </div>
        </div>
        <div className="text-right">
          <p className="font-bold text-sm text-[#2B3990]">PAYSLIP</p>
          <p className="text-xs text-gray-500">Pay Period: {period}</p>
        </div>
      </div>
      <div className="grid grid-cols-2 gap-x-6 gap-y-1 mb-4 text-sm">
        {[
          ["Employee ID", employee.id], ["Name", employee.name],
          ["Job Title", employee.job_title], ["Branch", branchName],
          ["Department", employee.department], ["KRA PIN", employee.kra_pin],
          ["NSSF No.", employee.nssf_no], ["NHIF No.", employee.nhif_no],
        ].map(([label, value]) => (
          <div key={label as string} className="flex gap-2">
            <span className="text-gray-500 min-w-[90px]">{label}:</span>
            <span className="font-medium">{value}</span>
          </div>
        ))}
      </div>
      <div className="grid grid-cols-2 gap-6 mb-4">
        <div>
          <p className="text-xs font-bold uppercase text-[#2B3990] mb-2 border-b border-gray-200 pb-1">Earnings</p>
          <div className="space-y-1 text-sm">
            {[["Basic Salary", slip.basic_salary], ["House Allowance", slip.house_allowance], ["Transport Allowance", slip.transport_allowance]].map(([l, v]) => (
              <div key={l as string} className="flex justify-between"><span className="text-gray-600">{l}</span><span>{formatCurrency(v as number)}</span></div>
            ))}
            <div className="flex justify-between font-bold border-t border-gray-200 pt-1 mt-1">
              <span>Gross Pay</span><span>{formatCurrency(slip.gross_salary)}</span>
            </div>
          </div>
        </div>
        <div>
          <p className="text-xs font-bold uppercase text-[#2B3990] mb-2 border-b border-gray-200 pb-1">Deductions</p>
          <div className="space-y-1 text-sm">
            {[["PAYE", slip.paye], ["NSSF (Employee)", slip.nssf], ["SHA (2.75%)", slip.sha], ["AHL (1.5%)", slip.ahl], ["NITA", slip.nita], ["Other", slip.other_deductions]].map(([l, v]) => (
              <div key={l as string} className="flex justify-between"><span className="text-gray-600">{l}</span><span className="text-red-600">{formatCurrency(v as number)}</span></div>
            ))}
            <div className="flex justify-between text-xs text-gray-500 mt-1">
              <span>Total Deductions</span>
              <span>{formatCurrency(slip.gross_salary - slip.net_salary)}</span>
            </div>
          </div>
        </div>
      </div>
      <div className="flex justify-between items-center bg-[#2B3990] text-white rounded-lg px-4 py-3">
        <span className="font-bold text-sm">NET PAY</span>
        <span className="font-bold text-lg">{formatCurrency(slip.net_salary, 2)}</span>
      </div>
      <p className="text-center text-xs text-gray-400 mt-3">Generated by Whiterose HRMIS · Computer generated — no signature required</p>
    </div>
  );
}

export default function Payslips() {
  const { employees } = useEmployees();
  const { branches } = useBranches();
  const [payslips, setPayslips] = useState<Payslip[]>([]);
  const [loading, setLoading] = useState(true);
  const [search, setSearch] = useState("");
  const [branchFilter, setBranchFilter] = useState("all");
  const [monthFilter, setMonthFilter] = useState("all");
  const [selected, setSelected] = useState<Payslip | null>(null);
  const printRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    supabase.from("payslips").select("*").order("created_at", { ascending: false })
      .then(({ data }) => { setPayslips(data ?? []); setLoading(false); });
  }, []);

  // If no saved payslips, generate from current employees for March 2026
  const displayPayslips = payslips.length > 0 ? payslips : employees.map((emp) => {
    const p = calculatePayroll(emp);
    return {
      id: emp.id,
      payroll_run_id: null,
      employee_id: emp.id,
      period_month: 3,
      period_year: 2026,
      gross_salary: p.gross,
      basic_salary: emp.basic_salary,
      house_allowance: emp.house_allowance,
      transport_allowance: emp.transport_allowance,
      paye: p.paye,
      nssf: p.nssf.employee,
      sha: p.sha,
      ahl: p.ahl.employee,
      nita: p.nita.employee,
      other_deductions: 0,
      net_salary: p.netPay,
      created_at: new Date().toISOString(),
    } as Payslip;
  });

  const filtered = displayPayslips.filter((s) => {
    const emp = employees.find((e) => e.id === s.employee_id);
    const branch = branches.find((b) => b.id === emp?.branch_id);
    const matchSearch = !search || emp?.name.toLowerCase().includes(search.toLowerCase()) || false;
    const matchBranch = branchFilter === "all" || branch?.id === branchFilter;
    const matchMonth = monthFilter === "all" || `${s.period_month}-${s.period_year}` === monthFilter;
    return matchSearch && matchBranch && matchMonth;
  });

  const handlePrint = () => {
    const content = printRef.current?.innerHTML;
    if (!content) return;
    const win = window.open("", "_blank", "width=700,height=600");
    if (!win) return;
    win.document.write(`<html><head><title>Payslip</title><style>body{font-family:sans-serif;margin:24px;font-size:13px}*{box-sizing:border-box}</style></head><body>${content}</body></html>`);
    win.document.close(); win.focus(); win.print(); win.close();
  };

  const selectedEmp = selected ? employees.find((e) => e.id === selected.employee_id) : null;
  const selectedBranch = selectedEmp ? branches.find((b) => b.id === selectedEmp.branch_id) : null;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="text-2xl font-bold text-foreground">Payslips</h1>
        <p className="text-sm text-muted-foreground">View and download employee payslips</p>
      </div>

      {/* Filters */}
      <div className="flex flex-wrap gap-3">
        <div className="relative flex-1 min-w-[200px] max-w-sm">
          <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
          <Input placeholder="Search employee…" className="pl-9" value={search} onChange={(e) => setSearch(e.target.value)} />
        </div>
        <Select value={branchFilter} onValueChange={setBranchFilter}>
          <SelectTrigger className="w-[180px]"><SelectValue placeholder="All Branches" /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Branches</SelectItem>
            {branches.map((b) => <SelectItem key={b.id} value={b.id}>{b.name}</SelectItem>)}
          </SelectContent>
        </Select>
        <Select value={monthFilter} onValueChange={setMonthFilter}>
          <SelectTrigger className="w-[150px]"><SelectValue placeholder="All Months" /></SelectTrigger>
          <SelectContent>
            <SelectItem value="all">All Months</SelectItem>
            <SelectItem value="3-2026">Mar 2026</SelectItem>
            <SelectItem value="2-2026">Feb 2026</SelectItem>
            <SelectItem value="1-2026">Jan 2026</SelectItem>
          </SelectContent>
        </Select>
      </div>

      {loading ? (
        <div className="rounded-xl border border-border bg-card shadow-sm overflow-hidden animate-pulse">
          {[...Array(6)].map((_, i) => <div key={i} className="h-12 border-b border-border/50 bg-muted/30" />)}
        </div>
      ) : filtered.length === 0 ? (
        <div className="rounded-xl border border-border bg-card p-10 text-center shadow-sm">
          <p className="text-sm text-muted-foreground">No payslips found.</p>
        </div>
      ) : (
        <div className="overflow-x-auto rounded-xl border border-border bg-card shadow-sm">
          <table className="w-full text-sm">
            <thead>
              <tr className="border-b border-border bg-muted/50">
                <th className="px-4 py-3 text-left font-medium text-muted-foreground">Employee</th>
                <th className="px-4 py-3 text-left font-medium text-muted-foreground">Branch</th>
                <th className="px-4 py-3 text-left font-medium text-muted-foreground">Period</th>
                <th className="px-4 py-3 text-right font-medium text-muted-foreground">Gross</th>
                <th className="px-4 py-3 text-right font-medium text-muted-foreground">Net Pay</th>
                <th className="px-4 py-3" />
              </tr>
            </thead>
            <tbody>
              {filtered.map((slip) => {
                const emp = employees.find((e) => e.id === slip.employee_id);
                const branch = branches.find((b) => b.id === emp?.branch_id);
                return (
                  <tr key={slip.id} className="border-b border-border/50 hover:bg-muted/30 transition-colors">
                    <td className="px-4 py-3">
                      <p className="font-medium text-card-foreground">{emp?.name ?? slip.employee_id}</p>
                      <p className="text-xs text-muted-foreground">{emp?.job_title}</p>
                    </td>
                    <td className="px-4 py-3 text-card-foreground">{branch?.name ?? "—"}</td>
                    <td className="px-4 py-3 text-card-foreground">{MONTHS[slip.period_month - 1]} {slip.period_year}</td>
                    <td className="px-4 py-3 text-right text-card-foreground">{formatCurrency(slip.gross_salary)}</td>
                    <td className="px-4 py-3 text-right font-semibold text-primary">{formatCurrency(slip.net_salary)}</td>
                    <td className="px-4 py-3">
                      <Button size="sm" variant="ghost" className="h-7 px-2 text-xs" onClick={() => setSelected(slip)}>
                        <FileText className="h-3.5 w-3.5 mr-1" /> View
                      </Button>
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </div>
      )}

      <Dialog open={!!selected} onOpenChange={(open) => { if (!open) setSelected(null); }}>
        <DialogContent className="max-w-2xl">
          <div className="flex items-center justify-between mb-4">
            <p className="text-sm font-semibold text-card-foreground">Payslip</p>
            <Button size="sm" variant="outline" onClick={handlePrint}><Printer className="mr-2 h-4 w-4" /> Print / PDF</Button>
          </div>
          <div ref={printRef}>
            {selected && selectedEmp && (
              <PayslipView slip={selected} employee={selectedEmp} branchName={selectedBranch?.name ?? "—"} />
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
