import jsPDF from "jspdf";

const COMPANY_NAME = "WHITEROSE VENYOU ENTERPRISES LIMITED";
const COMPANY_SUBTITLE = "NSSF Employer No: 2446614X | Mombasa, Kenya";
const FOOTER_TEXT = "Whiterose HRMIS | whiterose.co.ke | NSSF: 2446614X";
const PRIMARY = [43, 57, 144] as const;
const GOLD = [200, 150, 12] as const;
const LIGHT_GRAY = [130, 130, 130] as const;

export function buildReportName(reportName: string, period?: string) {
  const date = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  return ["Whiterose", reportName.replace(/\s+/g, ""), period ? period.replace(/\s+/g, "") : "", date]
    .filter(Boolean)
    .join("_");
}

export function brandedCsvHeader(reportName: string) {
  return [
    "# ============================================================",
    "# WHITEROSE VENYOU ENTERPRISES LIMITED",
    "# NSSF Employer No: 2446614X | Mombasa, Kenya",
    "# Generated by: Whiterose HRMIS",
    `# Generated on: ${new Date().toLocaleString("en-KE", { timeZone: "Africa/Nairobi" })}`,
    `# Report: ${reportName}`,
    "# CONFIDENTIAL - For authorized personnel only",
    "# ============================================================",
    "#",
  ].join("\n");
}

export function downloadBrandedCSV(
  reportName: string,
  headers: string[],
  rows: (string | number)[][][],
  period?: string,
) {
  const flatRows = rows.flat();
  const filename = `${buildReportName(reportName, period)}.csv`;
  const csvRows = [
    brandedCsvHeader(reportName + (period ? ` - ${period}` : "")),
    headers.join(","),
    ...flatRows.map((row) => row.map((cell) => `"${String(cell).replace(/"/g, '""')}"`).join(",")),
  ];

  const blob = new Blob([csvRows.join("\n")], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}

export function fmt(value: number) {
  return `KES ${value.toLocaleString("en-KE", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`;
}

export function createBrandedPdf(title: string, subtitle?: string) {
  const pdf = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = pdf.internal.pageSize.getWidth();

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(15);
  pdf.setTextColor(...PRIMARY);
  pdf.text(COMPANY_NAME, 14, 16);

  pdf.setDrawColor(...GOLD);
  pdf.setLineWidth(0.8);
  pdf.line(14, 19, pageWidth - 14, 19);

  pdf.setFont("helvetica", "normal");
  pdf.setFontSize(9);
  pdf.setTextColor(...LIGHT_GRAY);
  pdf.text(COMPANY_SUBTITLE, 14, 24);

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(14);
  pdf.setTextColor(20, 20, 20);
  pdf.text(title, 14, 32);

  if (subtitle) {
    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(9);
    pdf.setTextColor(...LIGHT_GRAY);
    pdf.text(subtitle, 14, 37);
  }

  pdf.setFont("helvetica", "bold");
  pdf.setFontSize(28);
  pdf.setTextColor(235, 235, 235);
  pdf.text("CONFIDENTIAL", pageWidth / 2, 150, { angle: 45, align: "center" });

  pdf.setTextColor(20, 20, 20);
  return pdf;
}

export function addPdfFooter(pdf: jsPDF) {
  const pageCount = pdf.getNumberOfPages();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  for (let page = 1; page <= pageCount; page += 1) {
    pdf.setPage(page);
    pdf.setDrawColor(...GOLD);
    pdf.setLineWidth(0.4);
    pdf.line(14, pageHeight - 15, pageWidth - 14, pageHeight - 15);

    pdf.setFont("helvetica", "normal");
    pdf.setFontSize(8);
    pdf.setTextColor(...LIGHT_GRAY);
    pdf.text(FOOTER_TEXT, 14, pageHeight - 10);
    pdf.text(`Page ${page} of ${pageCount}`, pageWidth - 14, pageHeight - 10, { align: "right" });
  }
}

export function saveBrandedPdf(pdf: jsPDF, reportName: string, period?: string) {
  addPdfFooter(pdf);
  pdf.save(`${buildReportName(reportName, period)}.pdf`);
}
