// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pynaxojadmyflnyyixse.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5bmF4b2phZG15ZmxueXlpeHNlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ2NzMwNDIsImV4cCI6MjA5MDI0OTA0Mn0.bkBuhvVKOSbHg0-q37Ke_SqfwTMTsYEO64AHCNrSQFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});